"""add_password_hash

Revision ID: 3db0c51d98a2
Revises: 52349948578c
Create Date: 2026-05-21 08:03:04.347536

"""
from alembic import op
import sqlalchemy as sa
from passlib.context import CryptContext



# revision identifiers, used by Alembic.
revision = '3db0c51d98a2'
down_revision = '52349948578c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(), nullable=True))

    pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")
    default_hash = pwd_context.hash("password123")
    op.execute(sa.text("UPDATE users SET password_hash = :hash WHERE password_hash IS NULL").bindparams(hash=default_hash))

    op.alter_column('users', 'password_hash', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
